import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import { cookies } from "next/headers";
import { SocketProvider } from "./socket-provider";
// export function getThemeClass() {
//   const hour = new Date().getHours();

//   if (hour >= 5 && hour < 8) return 'theme-sunrise';
//   if (hour >= 8 && hour < 16) return 'theme-midday';
//   if (hour >= 16 && hour < 19) return 'theme-sunset';
//   return 'theme-night';
// }

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose weights you need
  variable: '--font-poppins', // optional: to use with tailwind
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = (await cookies()).get('theme')?.value || 'theme-night';

  return (
    <Providers>
    <html lang="fr" className={themeCookie}>
    <meta charSet="UTF-8" />
      <body
        className={`${poppins.variable} flex items-center text-foreground w-full justify-center antialiased`}
      >
        <SocketProvider>
        <main className="w-full px-2 lg:px-0 lg:w-[80%]">
        {children}
        </main>
        </SocketProvider>
      </body>
    </html>
    </Providers>
  );
}
